### ISSUE TITLE
Auto completion in lowercase

### ISSUE THREAD

**Issue by Guibuu** [runxel/GDL-sublime#9]
Hi, I have just discovered this project and it's a bless! I'm trying to learn some GDL and this syntax highligthing is very helpful. Great work. Seriously.

In the [naming conventions](http://gdl.graphisoft.com/gdl-style-guide/naming-conventions) section of the Graphisoft's GDL Center, in 'Capitalization', Graphisoft recommends writing commands in lowercase. I too prefer that, makes the code more friendly. I'm curious, why did you decide the auto completion to suggest commands in uppercase? Could you… ahem… change that to lowercase? I think I know the answer, but still I have to try ;)

Thank you very much!

**Comment by runxel** [comment]
Guibuu, glad to hear that »GDL-sublime« is a help to you. Thanks a bunch!

So whats with the capitalization? That's the influence of the famous »GDL Cookbook« by David Nicholson-Cole. The author recommends writing GDL in uppercase – I know the official GS doc on that, tho. I sticked to him somehow.  
That being said I'm not a big fan of all-caps as well – since most modern language recommendations say lower-caps. So I might as well change that at some point in the future. Depends on my free time ;)

For completeness' sake here the full comment on that topic by DNC (p. 22, GDL Cookbook # 3):

> Typograpical note
In reading this you have already expressed a serious interest
in GDL – so let’s bring in a good discipline at the start.
Write all GDL commands in UPPER case, and all variables
(parameter names) and comments in lower case. The
machine is not case sensitive, but you are, and when reading
and debugging your scripts later, you will find it easier
if you follow this advice.
If you find yourself working on GDL as part of a team
you need to agree on a format, so this is a good rule to
follow. It is followed in the Cookbook.

**Comment by runxel** [comment]
done in v2.1.0 :)

**Comment by Guibuu** [comment]
That is **AWESOME**… I mean… **awesome** (in lower caps 😄 )

Also, thanks for explain me the original reason for the uppercases. It's a shame GDL Cookbook has become a little outdated, because there is little GDL documentation available.
